apiVersion: v1
kind: Service
metadata:
  name: offline-dictionary-service
  namespace: offline-dictionary
  labels:
    app: offline-dictionary
spec:
  selector:
    app: offline-dictionary
  ports:
  - port: 8099
    targetPort: 8099
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: offline-dictionary-ingress
  namespace: offline-dictionary
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 142.93.216.4  # Your server IP address
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: offline-dictionary-service
            port:
              number: 8099
