apiVersion: v1
kind: ConfigMap
metadata:
  name: offline-dictionary-config
  namespace: offline-dictionary
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/offline"
  DATABASE_NAME: "offline"
  APP_TITLE: "My Personal Dictionary"
  DEBUG: "False"
